alter table dw_erp_d_salesuser_base change d_date d_date int comment ' 数据日期  ';
alter table dw_erp_d_salesuser_base change id id string comment ' 员工id  ';
alter table dw_erp_d_salesuser_base change name name string comment ' 员工姓名  ';
alter table dw_erp_d_salesuser_base change username username string comment ' hpo账号  ';
alter table dw_erp_d_salesuser_base change sex sex string comment ' 员工性别  ';
alter table dw_erp_d_salesuser_base change entrydate entrydate string comment ' 入职日期  ';
alter table dw_erp_d_salesuser_base change formaldate formaldate int comment ' 转正日期 ';
alter table dw_erp_d_salesuser_base change status status int comment ' 0-试用,1-正式,2-离职  ';
alter table dw_erp_d_salesuser_base change account_status account_status int comment ' 员工状态 0-启用,1-禁用 ';
alter table dw_erp_d_salesuser_base change position_id position_id string comment ' 岗位ID  ';
alter table dw_erp_d_salesuser_base change position_name position_name string comment ' 岗位名称  ';
alter table dw_erp_d_salesuser_base change position_channel position_channel string comment ' 岗位通道  ';
alter table dw_erp_d_salesuser_base change position_channel_name position_channel_name string comment ' 岗位通道名称  ';
alter table dw_erp_d_salesuser_base change position_level position_level string comment ' 岗位级别  ';
alter table dw_erp_d_salesuser_base change position_level_name position_level_name string comment ' 岗位级别名称  ';
alter table dw_erp_d_salesuser_base change org_id org_id int comment ' 所在组织  ';
alter table dw_erp_d_salesuser_base change org_name org_name string comment ' 所在组织名称  ';
alter table dw_erp_d_salesuser_base change repertory_industry repertory_industry string comment ' 深耕行业 逗号分隔 ';
alter table dw_erp_d_salesuser_base change parent_salesuser_id parent_salesuser_id int comment ' 汇报对象  ';
alter table dw_erp_d_salesuser_base change parent_salesuser_name parent_salesuser_name string comment ' 汇报对象名称  ';
alter table dw_erp_d_salesuser_base change parent_salesuser_id_list parent_salesuser_id_list string comment ' 汇报对象及所有上级列表  ';
alter table dw_erp_d_salesuser_base change grade grade int comment ' 级别 ';
alter table dw_erp_d_salesuser_base change createtime createtime timestamp comment ' 创建时间  ';
alter table dw_erp_d_salesuser_base change modifytime modifytime timestamp comment ' 修改时间  ';
alter table dw_erp_d_salesuser_base change is_saleuser is_saleuser int comment ' 是否销售序列  ';
alter table dw_erp_d_salesuser_base change creation_timestamp creation_timestamp timestamp comment ' 时间戳  ';

alter table dw_erp_d_contract_base change id id int comment ' 主键id  ';
alter table dw_erp_d_contract_base change contract_no contract_no string comment ' 合同号  ';
alter table dw_erp_d_contract_base change customer_id customer_id int comment ' 客户id  ';
alter table dw_erp_d_contract_base change customer_linkman_id customer_linkman_id int comment ' 客户联系人  ';
alter table dw_erp_d_contract_base change type type int comment ' 合同类型: 0-猎聘通网上综合合同，1-诚聘通合同，2-薪酬报告，10-校园，11-rpo，12-广告，13-猎聘通，14-白领在线支付合同 ';
alter table dw_erp_d_contract_base change subtype subtype int comment ' 合同类型划分的小类型: 0-默认，1-rpo推荐免试，2-rpo推荐入职/猎头，3-rpo独家专场，4-rpo行业职能专场，5-rpo其他，6-lpol合同，7-白领在线支付合同 ';
alter table dw_erp_d_contract_base change action action int comment ' 合同产生类型 0-新签 1-补偿 3-销售确认(系统自动生成) ';
alter table dw_erp_d_contract_base change subaction subaction int comment ' 合同子类型 0-新签，1-能源转移，2-补偿，3-销售确认，4-资源置换 ';
alter table dw_erp_d_contract_base change status status int comment ' 合同主状态 0-编制中,1-我方盖章完成,2-已回执,3-已生效,4-作废 ';
alter table dw_erp_d_contract_base change audit_status audit_status int comment ' 合同审核状态 0-编制中,1-待审核,2-审核通过,3-驳回(可修改) ';
alter table dw_erp_d_contract_base change money money float comment ' 实际总金额  ';
alter table dw_erp_d_contract_base change secondparty_sign_id secondparty_sign_id int comment ' 签约人  ';
alter table dw_erp_d_contract_base change secondparty_sign_name secondparty_sign_name string comment ' 签约人名称  ';
alter table dw_erp_d_contract_base change secondparty_sign_pos_chnl secondparty_sign_pos_chnl string comment ' 签约人职位通道  ';
alter table dw_erp_d_contract_base change secondparty_sign_org secondparty_sign_org string comment ' 签约人所属组织  ';
alter table dw_erp_d_contract_base change secondparty_sign_org_name secondparty_sign_org_name string comment ' 签约人组织名称  ';
alter table dw_erp_d_contract_base change sign_date sign_date string comment ' 签约日期  ';
alter table dw_erp_d_contract_base change object_suit_id object_suit_id int comment ' 套餐id  ';
alter table dw_erp_d_contract_base change lpt_products_instance lpt_products_instance string comment ' 猎聘通产品实例列表  ';
alter table dw_erp_d_contract_base change ad_products_instance ad_products_instance string comment ' 广告产品实例列表  ';
alter table dw_erp_d_contract_base change srp_products_instance srp_products_instance string comment ' 薪酬报告产品实例列表  ';
alter table dw_erp_d_contract_base change clt_products_instance clt_products_instance string comment ' 诚猎通产品实例列表  ';
alter table dw_erp_d_contract_base change suit_products_instance suit_products_instance string comment ' 套餐产品实例列表  ';
alter table dw_erp_d_contract_base change expect_pay_date expect_pay_date string comment ' 预计付款日期  ';
alter table dw_erp_d_contract_base change pay_another pay_another int comment ' 是否代付 0 非代付,1代付  ';
alter table dw_erp_d_contract_base change memo memo string comment ' 备注  ';
alter table dw_erp_d_contract_base change creator_id creator_id int comment ' 当前维护人  ';
alter table dw_erp_d_contract_base change creator_name creator_name string comment ' 维护人名称  ';
alter table dw_erp_d_contract_base change creator_position_channel creator_position_channel string comment ' 维护人职位通道  ';
alter table dw_erp_d_contract_base change creator_org_id creator_org_id int comment ' 维护人所属组织  ';
alter table dw_erp_d_contract_base change creator_org_name creator_org_name string comment ' 维护人组织名称  ';
alter table dw_erp_d_contract_base change createtime createtime timestamp comment ' 创建日期  ';
alter table dw_erp_d_contract_base change modifytime modifytime timestamp comment ' 修改日期  ';
alter table dw_erp_d_contract_base change lpt_service_effect_date lpt_service_effect_date string comment ' 猎聘通服务生效时间  ';
alter table dw_erp_d_contract_base change lpt_service_expired_date lpt_service_expired_date string comment ' 猎聘通服务过期时间  ';
alter table dw_erp_d_contract_base change contract_effect_time contract_effect_time timestamp comment ' 猎聘通合同生效日期  ';
alter table dw_erp_d_contract_base change contract_sign_effect_mode contract_sign_effect_mode int comment ' 猎聘通合同上约定的生效模式  ';
alter table dw_erp_d_contract_base change contract_sign_effect_date contract_sign_effect_date string comment ' 猎聘通合同上约定的生效日期  ';
alter table dw_erp_d_contract_base change service_days service_days int comment ' 猎聘通合同服务天数  ';
alter table dw_erp_d_contract_base change res_cnt res_cnt int comment ' 猎聘通合同简历数  ';
alter table dw_erp_d_contract_base change job_cnt job_cnt int comment ' 猎聘通合同精英职位数  ';
alter table dw_erp_d_contract_base change intention_cnt intention_cnt int comment ' 猎聘通合同意向沟通数  ';
alter table dw_erp_d_contract_base change invite_apply_cnt invite_apply_cnt int comment ' 猎聘通合同邀请应聘数  ';
alter table dw_erp_d_contract_base change download_coupon_cnt download_coupon_cnt int comment ' 猎聘通合同下载券数数  ';
alter table dw_erp_d_contract_base change interview_coupon_cnt interview_coupon_cnt int comment ' 猎聘通合同面试快券数  ';
alter table dw_erp_d_contract_base change point_cnt point_cnt int comment ' 猎聘通合同积分数  ';
alter table dw_erp_d_contract_base change junior_res_cnt junior_res_cnt int comment ' 猎聘通合同白领简历数  ';
alter table dw_erp_d_contract_base change junior_job_cnt junior_job_cnt int comment ' 猎聘通合同白领职位数  ';
alter table dw_erp_d_contract_base change payment_days payment_days int comment ' 猎聘通合同账期天数  ';
alter table dw_erp_d_contract_base change input_lpt_money input_lpt_money float comment ' 猎聘通合同手工录入的lpt金额  ';
alter table dw_erp_d_contract_base change is_junior_contract is_junior_contract int comment ' 猎聘通合同是否白领合同  ';
alter table dw_erp_d_contract_base change creation_timestamp creation_timestamp timestamp comment ' 时间戳  ';

alter table dw_erp_d_customer_base change id id int comment ' 客户id  ';
alter table dw_erp_d_customer_base change name name string comment ' 姓名  ';
alter table dw_erp_d_customer_base change kind kind int comment ' 类别 0-潜在客户，1-意向客户，2-签约客户，9-回收站内客户,3-历史合作客户 ';
alter table dw_erp_d_customer_base change dq dq string comment ' 地区  ';
alter table dw_erp_d_customer_base change source source int comment ' 来源  1-点后呼入，3-网络注册，4-系统抓取，5-销售注册，6-手工导入，7-乐班班注册 ';
alter table dw_erp_d_customer_base change customer_category customer_category int comment ' 客户类别 0-目标，1-合作，2-断约，3-保留 ';
alter table dw_erp_d_customer_base change comp_industry comp_industry string comment ' 所属行业  ';
alter table dw_erp_d_customer_base change comp_scale comp_scale string comment ' 公司规模  ';
alter table dw_erp_d_customer_base change comp_kind comp_kind string comment ' 公司类型  ';
alter table dw_erp_d_customer_base change customer_type customer_type int comment ' 客户类型 0-新客户，1-a类活跃客户，2-b类活跃客户，3-c类活跃客户，4-d类活跃客户，5-浅度休眠客户，6-中度休眠客户，7-深度休眠客户，8-其他客户，9-战略客户 ';
alter table dw_erp_d_customer_base change reg_cap reg_cap string comment ' 注册资金  ';
alter table dw_erp_d_customer_base change reg_date reg_date string comment ' 注册日期  ';
alter table dw_erp_d_customer_base change fax fax string comment ' 传真  ';
alter table dw_erp_d_customer_base change addr addr string comment ' 地址  ';
alter table dw_erp_d_customer_base change zip zip string comment ' 邮编  ';
alter table dw_erp_d_customer_base change web web string comment ' 网址  ';
alter table dw_erp_d_customer_base change description description string comment ' 描述  ';
alter table dw_erp_d_customer_base change release_auto_type release_auto_type int comment ' 释放类型 1-自动，0-手动 ';
alter table dw_erp_d_customer_base change integrity integrity int comment ' 客户信息完整度 100是满分 ';
alter table dw_erp_d_customer_base change level level int comment ' 销售自己定义客户的级别 0-未认证客户，1-潜在客户，2-需求客户，3-意向客户，4-预测客户，5-已签约客户 ';
alter table dw_erp_d_customer_base change input_id input_id int comment ' 录入人  考核客户录入数 ';
alter table dw_erp_d_customer_base change service_user_id service_user_id int comment ' 招聘专员 gcdc  ';
alter table dw_erp_d_customer_base change parent_id parent_id int comment ' 上级机构id biz_customer上级id ';
alter table dw_erp_d_customer_base change packagecust_id packagecust_id int comment '主客户id -1-非打包客户,0-包的主客户,大于0-主客户id ';
alter table dw_erp_d_customer_base change root_id root_id int comment ' 集团机构id biz_customer的root_id ';
alter table dw_erp_d_customer_base change ecomp_id ecomp_id int comment ' 机构id   ecomp的ecomp_id';
alter table dw_erp_d_customer_base change ecomp_version ecomp_version int comment ' 企业版本 0-预览版，1-体验版， 2-精英版，3-白领版，4-精英过期版，5-白领过期版 ';
alter table dw_erp_d_customer_base change lp_privilege_status lp_privilege_status int comment ' 服务状态 0-试用，1-正式，2-作废 ';
alter table dw_erp_d_customer_base change creator_id creator_id int comment ' 当前维护人 所属销售顾问 ';
alter table dw_erp_d_customer_base change creator_name creator_name string comment ' 维护人名称  ';
alter table dw_erp_d_customer_base change position_channel position_channel string comment ' 维护人职位通道  ';
alter table dw_erp_d_customer_base change org_id org_id int comment ' 维护人所属组织  ';
alter table dw_erp_d_customer_base change org_name org_name string comment ' 维护人组织名称  ';
alter table dw_erp_d_customer_base change create_time create_time timestamp comment ' 创建日期  ';
alter table dw_erp_d_customer_base change creation_timestamp creation_timestamp timestamp comment ' 时间戳  ';

alter table dw_erp_d_godjob_list change d_date d_date int comment ' 统计日期 ';
alter table dw_erp_d_godjob_list change id id int comment ' 面试快服务主键 ';
alter table dw_erp_d_godjob_list change ejob_id ejob_id int comment ' 职位主键 ';
alter table dw_erp_d_godjob_list change ejob_title ejob_title string comment ' 职位名称 ';
alter table dw_erp_d_godjob_list change ecomp_id ecomp_id int comment ' 企业客户主键 ';
alter table dw_erp_d_godjob_list change ecomp_root_id ecomp_root_id int comment ' 企业集团客户主键 ';
alter table dw_erp_d_godjob_list change ecomp_name ecomp_name string comment ' 企业客户名称 ';
alter table dw_erp_d_godjob_list change industry industry string comment ' 行业 ';
alter table dw_erp_d_godjob_list change industry_name industry_name string comment ' 行业名称 ';
alter table dw_erp_d_godjob_list change create_time create_time timestamp comment ' 创建时间 ';
alter table dw_erp_d_godjob_list change is_add is_add int comment ' 是否当日新增 ';
alter table dw_erp_d_godjob_list change sales_id sales_id int comment ' 销售顾问主键 ';
alter table dw_erp_d_godjob_list change sales_name sales_name string comment ' 销售顾问名称 ';
alter table dw_erp_d_godjob_list change position_id position_id int comment ' 岗位主键 ';
alter table dw_erp_d_godjob_list change position_name position_name string comment ' 岗位名称 ';
alter table dw_erp_d_godjob_list change position_level position_level string comment ' 岗位级别 ';
alter table dw_erp_d_godjob_list change position_level_name position_level_name string comment ' 岗位级别名称 ';
alter table dw_erp_d_godjob_list change org_id org_id int comment ' 销售顾问所属组织主键 ';
alter table dw_erp_d_godjob_list change org_name org_name string comment ' 销售顾问所属组织名称 ';
alter table dw_erp_d_godjob_list change sales_group_id sales_group_id int comment ' 销售顾问汇报对象主键 ';
alter table dw_erp_d_godjob_list change sales_group_name sales_group_name string comment ' 销售顾问汇报对象名称 ';
alter table dw_erp_d_godjob_list change ge_status ge_status string comment ' 面试快服务状态 ';
alter table dw_erp_d_godjob_list change creation_timestamp creation_timestamp timestamp comment ' 时间戳 ';


alter table dw_erp_d_salesuser_act change d_date d_date int comment ' 统计日期 ';
alter table dw_erp_d_salesuser_act change sales_id sales_id int comment ' 销售顾问主键 ';
alter table dw_erp_d_salesuser_act change sales_name sales_name string comment ' 销售顾问姓名 ';
alter table dw_erp_d_salesuser_act change entrydate entrydate string comment ' 入职日期 ';
alter table dw_erp_d_salesuser_act change formaldate formaldate string comment ' 转正日期 ';
alter table dw_erp_d_salesuser_act change position_id position_id int comment ' 岗位主键 ';
alter table dw_erp_d_salesuser_act change position_name position_name string comment ' 岗位名称 ';
alter table dw_erp_d_salesuser_act change position_channel position_channel string comment ' 岗位渠道 ';
alter table dw_erp_d_salesuser_act change position_level position_level string comment ' 岗位级别 ';
alter table dw_erp_d_salesuser_act change org_id org_id int comment ' 组织主键 ';
alter table dw_erp_d_salesuser_act change org_name org_name string comment ' 组织名称 ';
alter table dw_erp_d_salesuser_act change repertory_industry repertory_industry string comment ' 深耕行业 ';
alter table dw_erp_d_salesuser_act change parent_salesuser_id parent_salesuser_id int comment ' 汇报对象主键 ';
alter table dw_erp_d_salesuser_act change parent_salesuser_name parent_salesuser_name string comment ' 汇报对象名称 ';
alter table dw_erp_d_salesuser_act change parent_salesuser_id_list parent_salesuser_id_list string comment ' 汇报对象及所有上级列表 ';
alter table dw_erp_d_salesuser_act change grade grade int comment ' 级次 ';
alter table dw_erp_d_salesuser_act change is_sales_agent is_sales_agent int comment ' 是否基础销售 ';
alter table dw_erp_d_salesuser_act change is_work_on is_work_on int comment ' 是否在职 ';
alter table dw_erp_d_salesuser_act change call_time_long call_time_long float comment ' 有效通话时长 ';
alter table dw_erp_d_salesuser_act change call_cus_cnt call_cus_cnt int comment ' 有效通话客户数 ';
alter table dw_erp_d_salesuser_act change call_rec_cnt call_rec_cnt int comment ' 有效通话次数 ';
alter table dw_erp_d_salesuser_act change visit_cus_cnt visit_cus_cnt int comment ' 拜访客户数 ';
alter table dw_erp_d_salesuser_act change input_cus_cnt input_cus_cnt int comment ' 录入客户数 ';
alter table dw_erp_d_salesuser_act change contract_new_cnt contract_new_cnt int comment ' 已签合同数 ';
alter table dw_erp_d_salesuser_act change contract_new_amount contract_new_amount float comment ' 已签约金额 ';
alter table dw_erp_d_salesuser_act change cus_contract_cnt cus_contract_cnt int comment ' 合作中客户数 ';
alter table dw_erp_d_salesuser_act change cus_expire_cnt cus_expire_cnt int comment ' 到期客户数 ';
alter table dw_erp_d_salesuser_act change cus_break_cnt cus_break_cnt int comment ' 断约客户数 ';
alter table dw_erp_d_salesuser_act change noincome_effect_cus_cnt noincome_effect_cus_cnt int comment ' 提前开通未回款客户数 ';
alter table dw_erp_d_salesuser_act change lpt_income lpt_income float comment ' 猎聘通合同回款金额 ';
alter table dw_erp_d_salesuser_act change all_income all_income float comment ' 所有合同回款金额 ';
alter table dw_erp_d_salesuser_act change add_cus_cnt add_cus_cnt int comment ' 面试快当日新增客户数 ';
alter table dw_erp_d_salesuser_act change add_ejob_cnt add_ejob_cnt int comment ' 面试快当日新增职位数 ';
alter table dw_erp_d_salesuser_act change service_cus_cnt service_cus_cnt int comment ' 面试快发起客户数 ';
alter table dw_erp_d_salesuser_act change service_ejob_cnt service_ejob_cnt int comment ' 面试快发起职位数 ';
alter table dw_erp_d_salesuser_act change creation_timestamp creation_timestamp timestamp comment ' 时间戳 ';
alter table dw_erp_d_salesuser_act change visit_cus_cnt_m visit_cus_cnt_m int comment ' 月累计拜访客户数 ';
alter table dw_erp_d_salesuser_act change input_cus_cnt_m input_cus_cnt_m int comment ' 月累计录入客户数 ';
alter table dw_erp_d_salesuser_act change contract_new_cnt_m contract_new_cnt_m int comment ' 月累计已签合同数 ';
alter table dw_erp_d_salesuser_act change contract_new_amount_m contract_new_amount_m float comment ' 月累计已签约金额 ';
alter table dw_erp_d_salesuser_act change all_income_m all_income_m float comment ' 月累计所有合同回款金额 ';

alter table dw_erp_d_contract_act change d_date d_date int comment ' 统计日期 ';
alter table dw_erp_d_contract_act change contract_id contract_id int comment ' 合同主键 ';
alter table dw_erp_d_contract_act change contract_no contract_no string comment ' 合同号 ';
alter table dw_erp_d_contract_act change contract_type contract_type string comment ' 合同类型 ';
alter table dw_erp_d_contract_act change service_effect_date service_effect_date string comment ' 服务生效时间 ';
alter table dw_erp_d_contract_act change service_expired_date service_expired_date string comment ' 服务失效时间 ';
alter table dw_erp_d_contract_act change sales_id sales_id int comment ' 销售顾问主键 ';
alter table dw_erp_d_contract_act change sales_name sales_name string comment ' 销售顾问名称 ';
alter table dw_erp_d_contract_act change sales_group_id sales_group_id int comment ' 销售顾问汇报对象 ';
alter table dw_erp_d_contract_act change sales_group_name sales_group_name string comment ' 销售顾问汇报对象名称 ';
alter table dw_erp_d_contract_act change position_level position_level string comment ' 销售顾问级别 ';
alter table dw_erp_d_contract_act change position_level_name position_level_name string comment ' 销售顾问级别名称 ';
alter table dw_erp_d_contract_act change org_id org_id int comment ' 部门主键 ';
alter table dw_erp_d_contract_act change org_name org_name string comment ' 部门名称 ';
alter table dw_erp_d_contract_act change customer_id customer_id int comment ' 客户主键 ';
alter table dw_erp_d_contract_act change customer_name customer_name string comment ' 客户名称 ';
alter table dw_erp_d_contract_act change comp_industry_code comp_industry_code string comment ' 客户行业编码 ';
alter table dw_erp_d_contract_act change comp_industry_name comp_industry_name string comment ' 客户行业名称 ';
alter table dw_erp_d_contract_act change is_contract_new is_contract_new int comment ' 是否新签 ';
alter table dw_erp_d_contract_act change contract_new_amount contract_new_amount float comment ' 新签合同金额 ';
alter table dw_erp_d_contract_act change is_lpt_in_service is_lpt_in_service int comment ' 是否合作中猎聘通客户 ';
alter table dw_erp_d_contract_act change is_lpt_expire is_lpt_expire int comment ' 是否到期 ';
alter table dw_erp_d_contract_act change is_lpt_break is_lpt_break int comment ' 是否断约 ';
alter table dw_erp_d_contract_act change is_noincome_effect is_noincome_effect int comment ' 是否提前开通未回款 ';
alter table dw_erp_d_contract_act change lpt_income lpt_income float comment ' 猎聘通合同回款金额 ';
alter table dw_erp_d_contract_act change all_income all_income float comment ' 合同回款金额 ';
alter table dw_erp_d_contract_act change creation_timestamp creation_timestamp timestamp comment ' 时间戳 ';
alter table dw_erp_d_contract_act change contract_money contract_money float comment ' 合同签约金额 ';
alter table dw_erp_d_contract_act change contract_status contract_status string comment ' 合同状态 ';
alter table dw_erp_d_contract_act change contract_sign_date contract_sign_date string comment ' 合同签约时间 ';
alter table dw_erp_d_contract_act change contract_createtime contract_createtime string comment ' 合同创建创建时间 ';
alter table dw_erp_d_contract_act change customer_sales_id customer_sales_id int comment ' 合同客户所属销售ID ';
alter table dw_erp_d_contract_act change customer_sales_name customer_sales_name string comment ' 合同客户所属销售姓名 ';
alter table dw_erp_d_contract_act change customer_position_level customer_position_level string comment ' 合同客户所属销售级次 ';
alter table dw_erp_d_contract_act change customer_position_level_name customer_position_level_name string comment ' 合同客户所属销售级次名称 ';
alter table dw_erp_d_contract_act change customer_org_id customer_org_id int comment ' 合同客户所属部门ID ';
alter table dw_erp_d_contract_act change customer_org_name customer_org_name string comment ' 合同客户所属部门名称 ';
alter table dw_erp_d_contract_act change lpt_income_m lpt_income_m float comment ' 月累计猎聘通合同回款金额 ';
alter table dw_erp_d_contract_act change all_income_m all_income_m float comment ' 月累计合同回款金额 ';

alter table dw_erp_d_customer_status change d_date d_date int comment ' 统计日期 ';
alter table dw_erp_d_customer_status change customer_id customer_id int comment ' 客户主键 ';
alter table dw_erp_d_customer_status change customer_name customer_name string comment ' 客户姓名 ';
alter table dw_erp_d_customer_status change comp_industry_code comp_industry_code string comment ' 客户行业编码 ';
alter table dw_erp_d_customer_status change comp_industry_name comp_industry_name string comment ' 客户行业名称 ';
alter table dw_erp_d_customer_status change sales_id sales_id int comment ' 所属销售顾问 ';
alter table dw_erp_d_customer_status change sales_name sales_name string comment ' 所属销售顾问姓名 ';
alter table dw_erp_d_customer_status change sales_group_id sales_group_id int comment ' 所属销售汇报对象 ';
alter table dw_erp_d_customer_status change sales_group_name sales_group_name string comment ' 所属销售汇报对象姓名 ';
alter table dw_erp_d_customer_status change position_level position_level string comment ' 所属销售级别 ';
alter table dw_erp_d_customer_status change position_level_name position_level_name string comment ' 所属销售级别名称 ';
alter table dw_erp_d_customer_status change org_id org_id int comment ' 所属部门 ';
alter table dw_erp_d_customer_status change org_name org_name string comment ' 所属部门名称 ';
alter table dw_erp_d_customer_status change lpt_service_effect_date lpt_service_effect_date string comment ' 猎聘通服务生效时间 ';
alter table dw_erp_d_customer_status change lpt_service_expired_date lpt_service_expired_date string comment ' 猎聘通服务失效时间 ';
alter table dw_erp_d_customer_status change is_lpt_in_service is_lpt_in_service int comment ' 是否合作中 ';
alter table dw_erp_d_customer_status change is_lpt_expire is_lpt_expire int comment ' 是否到期 ';
alter table dw_erp_d_customer_status change is_lpt_break is_lpt_break int comment ' 是否断约 ';
alter table dw_erp_d_customer_status change creation_timestamp creation_timestamp timestamp comment ' 时间戳 ';

alter table dw_erp_d_country_useravg change d_date d_date int comment ' 统计日期 ';
alter table dw_erp_d_country_useravg change position_channel position_channel string comment ' 岗位级别 ';
alter table dw_erp_d_country_useravg change avg_call_rec_cnt avg_call_rec_cnt int comment ' 平均有效通话次数 ';
alter table dw_erp_d_country_useravg change avg_call_time_long avg_call_time_long float comment ' 平均有效通话时长 ';
alter table dw_erp_d_country_useravg change avg_visit_cus_cnt avg_visit_cus_cnt int comment ' 平均拜访客户数 ';
alter table dw_erp_d_country_useravg change avg_input_cus_cnt avg_input_cus_cnt int comment ' 平均录入客户数 ';

alter table dw_erp_d_country_usermedian change d_date d_date int comment ' 统计日期 ';
alter table dw_erp_d_country_usermedian change position_channel position_channel string comment ' 岗位级别 ';
alter table dw_erp_d_country_usermedian change med_call_rec_cnt med_call_rec_cnt int comment ' 中位数有效通话次数 ';
alter table dw_erp_d_country_usermedian change med_call_time_long med_call_time_long float comment ' 中位数有效通话时长 ';
alter table dw_erp_d_country_usermedian change med_visit_cus_cnt med_visit_cus_cnt int comment ' 中位数拜访客户数 ';
alter table dw_erp_d_country_usermedian change med_input_cus_cnt med_input_cus_cnt int comment ' 中位数录入客户数 ';


alter table dw_erp_d_gcdcnewp_plan change task_id task_id int comment ' 任务ID ';
alter table dw_erp_d_gcdcnewp_plan change userc_id userc_id int comment ' 经理人ID ';
alter table dw_erp_d_gcdcnewp_plan change name name string comment ' 经理人姓名 ';
alter table dw_erp_d_gcdcnewp_plan change title title string comment ' 经理人当前职位名称 ';
alter table dw_erp_d_gcdcnewp_plan change industry industry string comment ' 目前行业 ';
alter table dw_erp_d_gcdcnewp_plan change resume_status resume_status int comment ' 经理人简历状态，1:无简历，2:简历不完整，低于60％，3:简历完整 ';
alter table dw_erp_d_gcdcnewp_plan change account_status account_status int comment ' 经理人账号状态，1:无账号，2:有账号 ';
alter table dw_erp_d_gcdcnewp_plan change task_receive_status task_receive_status int comment ' 任务领取状态，0:未领取，1:已领取';
alter table dw_erp_d_gcdcnewp_plan change userc_dq userc_dq string comment ' 拉新活动地区，BI数据则是经理人所在地区 ';
alter table dw_erp_d_gcdcnewp_plan change task_source task_source string comment ' 经理人来源，1:H5拉新，2:Excel人工，3:BI数据，4:APP地推上传，5:二维码全员拉新，6:品牌H5拉新 ';
alter table dw_erp_d_gcdcnewp_plan change task_creator_id task_creator_id int comment ' 任务当前维护人员ID ';
alter table dw_erp_d_gcdcnewp_plan change task_org_id task_org_id int comment ' 任务所在部门 ';
alter table dw_erp_d_gcdcnewp_plan change task_createtime task_createtime string comment ' 任务创建时间 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_id callplan_id int comment ' 拨打计划ID ';
alter table dw_erp_d_gcdcnewp_plan change callplan_calltime callplan_calltime string comment ' 计划拨打时间 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_finishtime callplan_finishtime string comment ' 拨打计划拉新成功时间 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_status callplan_status int comment ' 拨打计划任务状态，1:再次沟通，2:等待更新，3:新任务，4:拉新成功，5:拉入黑名单 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_industry callplan_industry string comment ' 拨打计划经理人行业 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_industry_name callplan_industry_name string comment ' 拨打计划经理人行业名称 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_dq callplan_dq string comment ' 拨打计划活动地区或经理人地区 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_dq_name callplan_dq_name string comment ' 拨打计划活动地区或经理人地区名称 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_creator_id callplan_creator_id int comment ' 拨打计划当前维护人员ID ';
alter table dw_erp_d_gcdcnewp_plan change callplan_creator_name callplan_creator_name string comment ' 拨打计划当前维护人员姓名 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_org_id callplan_org_id int comment ' 拨打计划所在部门 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_org_name callplan_org_name string comment ' 拨打计划所在部门名称 ';
alter table dw_erp_d_gcdcnewp_plan change callplan_createtime callplan_createtime string comment ' 拨打计划创建时间 ';
alter table dw_erp_d_gcdcnewp_plan change activity_id activity_id int comment ' 活动ID ';
alter table dw_erp_d_gcdcnewp_plan change activity_name activity_name string comment ' 活动名称 ';
alter table dw_erp_d_gcdcnewp_plan change activity_dq activity_dq string comment ' 活动地区 ';
alter table dw_erp_d_gcdcnewp_plan change activity_type activity_type int comment ' 活动类型，1:市场活动，2:品牌活动，3:BI线上流量，4:销售活动，5:线上BD活动 ';
alter table dw_erp_d_gcdcnewp_plan change activity_date activity_date string comment ' 活动日期 ';
alter table dw_erp_d_gcdcnewp_plan change activity_mscid activity_mscid string comment ' 媒体码 ';
alter table dw_erp_d_gcdcnewp_plan change activity_creator_id activity_creator_id int comment ' 活动当前维护人员ID ';
alter table dw_erp_d_gcdcnewp_plan change activity_org_id activity_org_id int comment ' 活动所在部门 ';
alter table dw_erp_d_gcdcnewp_plan change activity_createtime activity_createtime string comment ' 活动创建时间 ';
alter table dw_erp_d_gcdcnewp_plan change creation_timestamp creation_timestamp timestamp comment ' 时间戳 ';

alter table dw_erp_d_gcdc_newpull change d_date d_date int comment ' 统计日期 ';
alter table dw_erp_d_gcdc_newpull change gcdc_id gcdc_id int comment ' GCDC顾问 ';
alter table dw_erp_d_gcdc_newpull change gcdc_name gcdc_name string comment ' GCDC顾问名称 ';
alter table dw_erp_d_gcdc_newpull change org_id org_id int comment ' 所属部门 ';
alter table dw_erp_d_gcdc_newpull change org_name org_name string comment ' 所属部门名称 ';
alter table dw_erp_d_gcdc_newpull change industry industry string comment ' 经理人行业 ';
alter table dw_erp_d_gcdc_newpull change industry_name industry_name string comment ' 经理人行业名称 ';
alter table dw_erp_d_gcdc_newpull change dq dq string comment ' 活动城市或经理人城市 ';
alter table dw_erp_d_gcdc_newpull change dq_name dq_name string comment ' 城市名称 ';
alter table dw_erp_d_gcdc_newpull change activity_type activity_type string comment ' 拉新活动类型 ';
alter table dw_erp_d_gcdc_newpull change activity_type_name activity_type_name string comment ' 拉新活动类型名称 ';
alter table dw_erp_d_gcdc_newpull change valid_call_rec_cnt valid_call_rec_cnt int comment ' 有效沟通数 ';
alter table dw_erp_d_gcdc_newpull change valid_call_c_cnt valid_call_c_cnt int comment ' 有效覆盖数 ';
alter table dw_erp_d_gcdc_newpull change call_c_cnt call_c_cnt int comment ' 已覆盖人数 ';
alter table dw_erp_d_gcdc_newpull change call_rec_cnt call_rec_cnt int comment ' 已沟通次数 ';
alter table dw_erp_d_gcdc_newpull change finish_res_c_cnt finish_res_c_cnt int comment ' 在线完成数 ';
alter table dw_erp_d_gcdc_newpull change finish_level6_res_cnt finish_level6_res_cnt int comment ' 6级简历的数量 ';
alter table dw_erp_d_gcdc_newpull change finish_level5_res_cnt finish_level5_res_cnt int comment ' 5级简历的数量 ';
alter table dw_erp_d_gcdc_newpull change finish_level4_res_cnt finish_level4_res_cnt int comment ' 4级简历的数量 ';
alter table dw_erp_d_gcdc_newpull change finish_level3_res_cnt finish_level3_res_cnt int comment ' 3级简历的数量 ';
alter table dw_erp_d_gcdc_newpull change finish_level2_res_cnt finish_level2_res_cnt int comment ' 2级简历的数量 ';
alter table dw_erp_d_gcdc_newpull change finish_level1_res_cnt finish_level1_res_cnt int comment ' 1级简历的数量 ';
alter table dw_erp_d_gcdc_newpull change invite_c_cnt invite_c_cnt int comment ' 发送邀请数 ';
alter table dw_erp_d_gcdc_newpull change finish_invite_c_cnt finish_invite_c_cnt int comment ' 邀请完成数 ';
alter table dw_erp_d_gcdc_newpull change finish_res_cnt finish_res_cnt int comment ' 简历完成总数 ';
alter table dw_erp_d_gcdc_newpull change finish_biz_res_cnt finish_biz_res_cnt int comment ' 商业简历完善数 ';
alter table dw_erp_d_gcdc_newpull change finish_task_c_cnt finish_task_c_cnt int comment ' 当天领取任务的覆盖数 ';
alter table dw_erp_d_gcdc_newpull change call_plan_c_cnt call_plan_c_cnt int comment ' 今日待沟通总数 ';

alter table dw_b_d_ejob_base change ejob_id ejob_id int  comment '职位标识';
alter table dw_b_d_ejob_base change user_id user_id int  comment '公司hr';
alter table dw_b_d_ejob_base change ecomp_id ecomp_id int  comment '所属公司';
alter table dw_b_d_ejob_base change ecomp_root_id ecomp_root_id int  comment '所属集团';
alter table dw_b_d_ejob_base change ecomp_industrys ecomp_industrys string  comment '所属公司行业';
alter table dw_b_d_ejob_base change ecomp_industry_first ecomp_industry_first string  comment '所属公司行业第一个';
alter table dw_b_d_ejob_base change ejob_title ejob_title string  comment '职位名称';
alter table dw_b_d_ejob_base change ejob_jobtitle ejob_jobtitle string  comment '职位所属分类';
alter table dw_b_d_ejob_base change ejob_jobtitle_first ejob_jobtitle_first string  comment '职位所属分类第一个';
alter table dw_b_d_ejob_base change ejob_closedate ejob_closedate string  comment '职位截止日期';
alter table dw_b_d_ejob_base change ejob_dq ejob_dq string  comment '职位所在地区';
alter table dw_b_d_ejob_base change ejob_dq_first ejob_dq_first string  comment '职位所在地区第一个';
alter table dw_b_d_ejob_base change ejob_auditflag ejob_auditflag string  comment '职位审核状态:0：未审核1：审核已通过2：审核未通过';
alter table dw_b_d_ejob_base change ejob_status ejob_status string  comment '职位发布状态0：发布中1：已经暂停2：未发布3：发布结束';
alter table dw_b_d_ejob_base change ejob_privacyreq ejob_privacyreq string  comment '0--不保密， 1--保密';
alter table dw_b_d_ejob_base change ejob_createtime ejob_createtime timestamp  comment '职位发布时间';
alter table dw_b_d_ejob_base change ejob_salarydiscuss ejob_salarydiscuss string  comment '薪资面议：0：非面议1：面议';
alter table dw_b_d_ejob_base change ejob_salarylow ejob_salarylow float  comment '职位年薪的下限-旧';
alter table dw_b_d_ejob_base change ejob_salaryhigh ejob_salaryhigh float  comment '职位年薪的上限-旧';
alter table dw_b_d_ejob_base change ejob_monthlysalary_low ejob_monthlysalary_low float  comment '职位月薪的上限';
alter table dw_b_d_ejob_base change ejob_monthlysalary_high ejob_monthlysalary_high  float  comment '职位月薪的上限';
alter table dw_b_d_ejob_base change ejob_salary_month ejob_salary_month int comment '薪资的月数';
alter table dw_b_d_ejob_base change ejob_salarylow ejob_salarylow float  comment '职位年薪的下限(最低月薪*月数或最低年薪-旧)';
alter table dw_b_d_ejob_base change ejob_salaryhigh ejob_salaryhigh float  comment '职位年薪的上限(最高月薪*月数或最高年薪-旧)';
alter table dw_b_d_ejob_base change modifytime modifytime timestamp  comment '用户修改时间';
alter table dw_b_d_ejob_base change createtime createtime timestamp  comment '用户创建时间';
alter table dw_b_d_ejob_base change ejob_filterapplyflag ejob_filterapplyflag string  comment '限制人选应聘(发布职位勾选项)';
alter table dw_b_d_ejob_base change ejob_level ejob_level string  comment '历史：0 初级职位 1 中高级职位 新20160421后: 0-白领  1-精英';
alter table dw_b_d_ejob_base change ejob_topflag ejob_topflag string  comment '是否置顶 0：否 1：是';
alter table dw_b_d_ejob_base change detail_workyears detail_workyears int  comment '总工作年限';
alter table dw_b_d_ejob_base change detail_sex detail_sex string  comment '性别';
alter table dw_b_d_ejob_base change detail_agelow detail_agelow int  comment '最低年龄';
alter table dw_b_d_ejob_base change detail_agehigh detail_agehigh int  comment '最高年龄';
alter table dw_b_d_ejob_base change detail_edulevel detail_edulevel string  comment '学历';
alter table dw_b_d_ejob_base change detail_edulevel_tz detail_edulevel_tz string  comment '是否统招0:不限1:是';
alter table dw_b_d_ejob_base change detail_report2 detail_report2 string  comment '汇报对象';
alter table dw_b_d_ejob_base change detail_subordinate detail_subordinate string  comment '下属人数';
alter table dw_b_d_ejob_base change detail_special detail_special string  comment '专业';
alter table dw_b_d_ejob_base change detail_importurl detail_importurl string  comment '当职位是采集过来的时候，它表示采集的url地址';
alter table dw_b_d_ejob_base change detail_source detail_source string  comment '职位来源0:猎聘网1:51job.com 2:zhaopin.com 3:chinahr.com 4:职位班级 5:lagou.com';
alter table dw_b_d_ejob_base change detail_industrys detail_industrys string  comment '职位期望行业';
alter table dw_b_d_ejob_base change detail_industrys_first detail_industrys_first string  comment '职位期望行业第一个';
alter table dw_b_d_ejob_base change feedback_period feedback_period int comment '反馈时长';
alter table dw_b_d_ejob_base change ejob_salarylow ejob_salarylow float  comment '职位年薪的下限(旧)';
alter table dw_b_d_ejob_base change ejob_salaryhigh ejob_salaryhigh float  comment '职位年薪的上限(旧)';
alter table dw_b_d_ejob_base change ejob_salarylow_new ejob_salarylow_new float  comment '职位年薪的下限(最低月薪*月数或最低年薪)';
alter table dw_b_d_ejob_base change ejob_salaryhigh_new ejob_salaryhigh_new float  comment '职位年薪的上限(最高月薪*月数或最高年薪)';

alter table dw_c_d_res_base change res_id res_id int comment '简历主键';
alter table dw_c_d_res_base change user_id user_id int comment '用户主键';
alter table dw_c_d_res_base change res_caption res_caption string comment '简历名称';
alter table dw_c_d_res_base change res_lockflag res_lockflag string comment '简历锁定标记 0:解锁 1:锁定 ';
alter table dw_c_d_res_base change res_langkind res_langkind string comment '简历语言 0:中文 1:英文 ';
alter table dw_c_d_res_base change res_format res_format string comment '简历格式 0:老的 1:新的 ';
alter table dw_c_d_res_base change res_source res_source string comment '简历来源 来源 0:HPO 1:猎聘网 2:cpc 3:qc 4:zp 5:bo 6:td 7:xy 9:其他 10: HR upload ';
alter table dw_c_d_res_base change res_category res_category string comment '简历状态 0:审核不通过 8:草稿 9:待审核状态 1:中级人才 2:高级人才 ';
alter table dw_c_d_res_base change res_createtime res_createtime string comment '简历创建时间';
alter table dw_c_d_res_base change res_modifiedtime res_modifiedtime string comment '修改时间 修改时间 ';
alter table dw_c_d_res_base change res_audittime res_audittime string comment '完整简历审核通过的时间 变为完整简历的时间 ';
alter table dw_c_d_res_base change res_biz_audittime res_biz_audittime string comment '商业简历审核通过的时间-已失效 变为商业简历的时间-已失效 ';
alter table dw_c_d_res_base change res_default_flag res_default_flag string comment '默认简历标记 1:默认简历 ';
alter table dw_c_d_res_base change res_level res_level int comment '简历等级 -1:未分级简历、1:初级简历、2/3/4/5级简历为中高端简历 ';
alter table dw_c_d_res_base change res_bgcheck res_bgcheck string comment '简历认证状态 认证状态 0 未认证 1 认证通过 ';
alter table dw_c_d_res_base change res_type res_type string comment '简历类型 类型 0:xy 1:猎聘 ';
alter table dw_c_d_res_base change res_kind res_kind string comment '简历种类 类型 0:猎聘简历 1:猎头或者企业下载的简历、rts简历 2:其它 ';
alter table dw_c_d_res_base change res_integrity_flag res_integrity_flag string comment '简历完整度 简历完整度 ';
alter table dw_c_d_res_base change integrity_flag integrity_flag string comment '用户及简历完整度 用户及简历完整度 ';
alter table dw_c_d_res_base change user_integrity_flag user_integrity_flag string comment '用户资料完整度 CALC_RES_COMPLETE_RATE计算完整度 ';
alter table dw_c_d_res_base change c_createtime c_createtime string comment '用户创建时间';
alter table dw_c_d_res_base change c_kind c_kind string comment '是否金卡用户 0:非金卡会员,1:金卡会员 ';
alter table dw_c_d_res_base change c_industry c_industry string comment '目前所在行业分类code码';
alter table dw_c_d_res_base change c_jobtitle c_jobtitle string comment '目前所任职位分类code码';
alter table dw_c_d_res_base change c_workyear c_workyear int comment '开始工作的年份 默认值1900 ';
alter table dw_c_d_res_base change c_title c_title string comment '目前职位名称';
alter table dw_c_d_res_base change c_company c_company string comment '目前所在公司名称';
alter table dw_c_d_res_base change c_dq c_dq string comment '经理人所在地区code码 9位 ';
alter table dw_c_d_res_base change c_sex c_sex string comment '性别 男, 女, 9 ';
alter table dw_c_d_res_base change c_edulevel c_edulevel string comment '经理人最高学历 090:初中,080:高中,070:中技,060:中专,050:大专,040:本科,030:硕士,020:MBA,010:博士,005:博士后 ';
alter table dw_c_d_res_base change c_edulevel_tz c_edulevel_tz string comment '经理人最高学历是否统招 1:统招 0:非统招 ';
alter table dw_c_d_res_base change c_birth_year c_birth_year string comment '出生年份 默认值1900 ';
alter table dw_c_d_res_base change c_marriage c_marriage string comment '婚否 0:未婚, 1:已婚, 9:不详 ';
alter table dw_c_d_res_base change c_nowsalary c_nowsalary int comment '目前月薪';
alter table dw_c_d_res_base change c_salmonths c_salmonths int comment '发薪月数';
alter table dw_c_d_res_base change c_hope c_hope string comment '求职状态 0:目前在职，有好机会可以看看, 1:目前离职，随时可以谈新机会, 2:目前在职，希望尽快寻找新机会 ';
alter table dw_c_d_res_base change c_namecardflag c_namecardflag string comment '是否已填写名片 0:没填 1:已填 ';
alter table dw_c_d_res_base change c_telcheckflag c_telcheckflag string comment '手机号码是否验证 0:未验证，1:已验证 ';
alter table dw_c_d_res_base change c_emailcheckflag c_emailcheckflag string comment 'email是否验证 0:未验证，1:已验证 ';
alter table dw_c_d_res_base change c_school_kind c_school_kind string comment '学校类型 0:common 1:211 2:985 ';
alter table dw_c_d_res_base change c_company_kind c_company_kind string comment '公司类型 8位字符串，每一位表示一种公司类型的属性，只有2个取值0和1，0表示否，1表示是。 前3位依次是：世界500强、中国500强、上市公司。后5位保留 ';
alter table dw_c_d_res_base change c_household c_household string comment '户口';
alter table dw_c_d_res_base change c_nationality c_nationality string comment '国籍';
alter table dw_c_d_res_base change reg_device reg_device string comment '注册终端';
alter table dw_c_d_res_base change reg_mscid reg_mscid string comment '注册媒体码';
alter table dw_c_d_res_base change reg_plan reg_plan string comment '';
alter table dw_c_d_res_base change reg_unit reg_unit string comment '';
alter table dw_c_d_res_base change reg_keyword reg_keyword string comment '';
alter table dw_c_d_res_base change want_monthsalary want_monthsalary int comment '期望月薪';
alter table dw_c_d_res_base change want_salmonths want_salmonths int comment '期望月数';
alter table dw_c_d_res_base change want_industry want_industry string comment '期望行业分类代码';
alter table dw_c_d_res_base change want_industry_first want_industry_first string comment '第一期望行业分类代码 取第一个行业 ';
alter table dw_c_d_res_base change want_jobtitle want_jobtitle string comment '期望职能分类代码';
alter table dw_c_d_res_base change want_jobtitle_first want_jobtitle_first string comment '第一期望职能分类代码 取第一个职能 ';
alter table dw_c_d_res_base change want_dq want_dq string comment '期望工作地点代码';
alter table dw_c_d_res_base change want_dq_first want_dq_first string comment '第一期望工作地点代码 取第一个地区 ';
alter table dw_c_d_res_base change want_venture_company want_venture_company string comment '是否期望进入创业型公司 0 否, 1 是 ';
alter table dw_c_d_res_base change secret_openwho secret_openwho string comment '我希望简历被谁看到 0:猎头顾问和企业HR都能看到 1:仅猎头顾问能看到 2:仅企业HR能看到 3:暂时无跳槽需求，猎头顾问和企业HR都不能看到 ';
alter table dw_c_d_res_base change secret_name secret_name string comment '简历隐私设置 姓名  0:显示全名 1:显示先生或女士 ';
alter table dw_c_d_res_base change secret_yearsalary secret_yearsalary string comment '简历隐私设置 年薪 0:显示 1:隐藏 ';
alter table dw_c_d_res_base change secret_contactway secret_contactway string comment '简历隐私设置 联系方式 0:显示全部联系方式 1:只显示手机 2:只显示邮箱 ';
alter table dw_c_d_res_base change secret_e_shield secret_e_shield string comment '简历隐私设置 企业屏蔽 0:让所有企业都能搜索到我 1:我不希望某些企业搜索到我 ';
alter table dw_c_d_res_base change secret_keys secret_keys string comment '企业屏蔽的关键词 当企业用户查看经理人简历时, 如果企业名称中含有过滤关键词, 简历就不能被企业查看,多个以"#!#"隔开 ';
alter table dw_c_d_res_base change secret_contactflag secret_contactflag string comment '建议联系时间 0:随时可以打电话联系我, 1:请先发短信给我，我在方便的时候会回您, 2:自定义时间 ';
alter table dw_c_d_res_base change secret_contactmemo secret_contactmemo string comment '建议联系时间的自定义时间 secret_contactflag=2, 自定义的时间 ';
alter table dw_c_d_res_base change secret_wantsalary secret_wantsalary string comment '简历隐私设置 期望月薪  0:显示 1:隐藏 ';
alter table dw_c_d_res_base change secret_sns secret_sns string comment '人脉认证状态  1：开启  0：关闭 ';
alter table dw_c_d_res_base change secret_sns2 secret_sns2 string comment '人脉隐私设置 0:不接受任何人的好友请求,1:所有人,2:二度人脉好友 ';
alter table dw_c_d_res_base change secret_card secret_card string comment '名片隐私设置 0:只有一度人脉可以看到，1:所有人都能看到，2:我的一度，二度人脉能看到 ';
alter table dw_c_d_res_base change creation_timestamp creation_timestamp timestamp comment '时间戳';

alter table dw_c_d_user_base change user_id user_id int comment '用户主键';
alter table dw_c_d_user_base change createtime createtime string comment '用户创建时间';
alter table dw_c_d_user_base change c_kind c_kind string comment '是否金卡用户 0:非金卡会员,1:金卡会员 ';
alter table dw_c_d_user_base change c_industry c_industry string comment '目前所在行业分类code码';
alter table dw_c_d_user_base change c_jobtitle c_jobtitle string comment '目前所任职位分类code码';
alter table dw_c_d_user_base change c_workyear c_workyear int comment '开始工作的年份 默认值1900 ';
alter table dw_c_d_user_base change c_title c_title string comment '目前职位名称';
alter table dw_c_d_user_base change c_company c_company string comment '目前所在公司名称';
alter table dw_c_d_user_base change c_dq c_dq string comment '经理人所在地区code码 9位 ';
alter table dw_c_d_user_base change c_sex c_sex string comment '性别 男, 女, 9 ';
alter table dw_c_d_user_base change c_edulevel c_edulevel string comment '经理人最高学历090:初中,080:高中,070:中技,060:中专,050:大专,040:本科,030:硕士,020:MBA,010:博士,005:博士后 ';
alter table dw_c_d_user_base change c_edulevel_tz c_edulevel_tz string comment '经理人最高学历是否统招 1:统招 0:非统招 ';
alter table dw_c_d_user_base change c_birth_year c_birth_year string comment '出生年份 默认值1900 ';
alter table dw_c_d_user_base change c_marriage c_marriage string comment '婚否 0:未婚, 1:已婚, 9:不详 ';
alter table dw_c_d_user_base change c_nowsalary c_nowsalary int comment '目前月薪';
alter table dw_c_d_user_base change c_salmonths c_salmonths int comment '发薪月数';
alter table dw_c_d_user_base change c_hope c_hope string comment '求职状态 0:目前在职，有好机会可以看看, 1:目前离职，随时可以谈新机会, 2:目前在职，希望尽快寻找新机会 ';
alter table dw_c_d_user_base change c_namecardflag c_namecardflag string comment '是否已填写名片 0:没填 1:已填 ';
alter table dw_c_d_user_base change c_telcheckflag c_telcheckflag string comment '手机号码是否验证 0:未验证，1:已验证 ';
alter table dw_c_d_user_base change c_emailcheckflag c_emailcheckflag string comment 'email是否验证 0:未验证，1:已验证 ';
alter table dw_c_d_user_base change c_school_kind c_school_kind string comment '学校类型 0:common 1:211 2:985 ';
alter table dw_c_d_user_base change c_company_kind c_company_kind string comment '公司类型 8位字符串，每一位表示一种公司类型的属性，只有2个取值0和1，0表示否，1表示是。 前3位依次是：世界500强、中国500强、上市公司。后5位保留 ';
alter table dw_c_d_user_base change c_household c_household string comment '户口';
alter table dw_c_d_user_base change c_nationality c_nationality string comment '国籍';
alter table dw_c_d_user_base change reg_device reg_device string comment '注册终端';
alter table dw_c_d_user_base change reg_mscid reg_mscid string comment '注册媒体码';
alter table dw_c_d_user_base change reg_plan reg_plan string comment '';
alter table dw_c_d_user_base change reg_unit reg_unit string comment '';
alter table dw_c_d_user_base change reg_keyword reg_keyword string comment '';
alter table dw_c_d_user_base change want_monthsalary want_monthsalary int comment '期望月薪';
alter table dw_c_d_user_base change want_salmonths want_salmonths int comment '期望月数';
alter table dw_c_d_user_base change want_industry want_industry string comment '期望行业分类代码';
alter table dw_c_d_user_base change want_industry_first want_industry_first string comment '第一期望行业分类代码 取第一个行业 ';
alter table dw_c_d_user_base change want_jobtitle want_jobtitle string comment '期望职能分类代码';
alter table dw_c_d_user_base change want_jobtitle_first want_jobtitle_first string comment '第一期望职能分类代码 取第一个职能 ';
alter table dw_c_d_user_base change want_dq want_dq string comment '期望工作地点代码';
alter table dw_c_d_user_base change want_dq_first want_dq_first string comment '第一期望工作地点代码 取第一个地区 ';
alter table dw_c_d_user_base change want_venture_company want_venture_company string comment '是否期望进入创业型公司 0 否, 1 是 ';
alter table dw_c_d_user_base change integrity_flag integrity_flag string comment '用户资料完整度 CALC_RES_COMPLETE_RATE计算完整度 ';
alter table dw_c_d_user_base change secret_openwho secret_openwho string comment '我希望简历被谁看到 0:猎头顾问和企业HR都能看到 1:仅猎头顾问能看到 2:仅企业HR能看到 3:暂时无跳槽需求，猎头顾问和企业HR都不能看到 ';
alter table dw_c_d_user_base change secret_name secret_name string comment '简历隐私设置 姓名  0:显示全名 1:显示先生或女士 ';
alter table dw_c_d_user_base change secret_yearsalary secret_yearsalary string comment '简历隐私设置 年薪 0:显示 1:隐藏 ';
alter table dw_c_d_user_base change secret_contactway secret_contactway string comment '简历隐私设置 联系方式 0:显示全部联系方式 1:只显示手机 2:只显示邮箱 ';
alter table dw_c_d_user_base change secret_e_shield secret_e_shield string comment '简历隐私设置 企业屏蔽 0:让所有企业都能搜索到我 1:我不希望某些企业搜索到我 ';
alter table dw_c_d_user_base change secret_keys secret_keys string comment '企业屏蔽的关键词 当企业用户查看经理人简历时, 如果企业名称中含有过滤关键词, 简历就不能被企业查看,多个以"#!#"隔开 ';
alter table dw_c_d_user_base change secret_contactflag secret_contactflag string comment '建议联系时间 0:随时可以打电话联系我, 1:请先发短信给我，我在方便的时候会回您, 2:自定义时间 ';
alter table dw_c_d_user_base change secret_contactmemo secret_contactmemo string comment '建议联系时间的自定义时间 secret_contactflag=2, 自定义的时间 ';
alter table dw_c_d_user_base change secret_wantsalary secret_wantsalary string comment '简历隐私设置 期望月薪  0:显示 1:隐藏 ';
alter table dw_c_d_user_base change secret_sns secret_sns string comment '人脉认证状态  1：开启  0：关闭 ';
alter table dw_c_d_user_base change secret_sns2 secret_sns2 string comment '人脉隐私设置 0:不接受任何人的好友请求,1:所有人,2:二度人脉好友 ';
alter table dw_c_d_user_base change secret_card secret_card string comment '名片隐私设置 0:只有一度人脉可以看到，1:所有人都能看到，2:我的一度，二度人脉能看到 ';
alter table dw_c_d_user_base change creation_timestamp creation_timestamp timestamp comment '时间戳';

alter table dw_c_d_usermsc_act change user_id user_id int comment '用户主键';
alter table dw_c_d_usermsc_act change action_source action_source string comment '终端类型';
alter table dw_c_d_usermsc_act change msc_id msc_id string comment '媒体码';
alter table dw_c_d_usermsc_act change res_refresh_cnt res_refresh_cnt int comment '简历刷新次数';
alter table dw_c_d_usermsc_act change res_update_cnt res_update_cnt int comment '简历修改次数';
alter table dw_c_d_usermsc_act change res_full_return res_full_return int comment '完整回归简历数';
alter table dw_c_d_usermsc_act change res_biz_return res_biz_return int comment '商业回归简历数';
alter table dw_c_d_usermsc_act change creation_timestamp creation_timestamp timestamp comment '时间戳';

alter table dw_c_d_appuser_base change user_id user_id int comment '用户主键';
alter table dw_c_d_appuser_base change first_login_day first_login_day string comment '首次登陆时间';
alter table dw_c_d_appuser_base change first_login_device first_login_device int comment '首次登陆终端';
alter table dw_c_d_appuser_base change last_login_day last_login_day string comment '最近一次登陆时间';
alter table dw_c_d_appuser_base change last_login_device last_login_device int comment '最近一次登陆终端';
alter table dw_c_d_appuser_base change reg_device reg_device int comment '注册终端';
alter table dw_c_d_appuser_base change reg_datetime reg_datetime string comment '注册时间';
alter table dw_c_d_appuser_base change creation_timestamp creation_timestamp timestamp comment '时间戳';
alter table dw_c_d_appuser_base change p_date p_date int comment '日期分区';
