create table dw_erp_d_salesuser_act
(
	d_date int,
	sales_id int,
	sales_name varchar(100),
	entrydate varchar(10),
	formaldate varchar(10),
	position_id int,
	position_name varchar(100),
	position_channel varchar(100),
	position_level varchar(100),
	org_id int,
	org_name varchar(300),
	repertory_industry varchar(50),
	parent_salesuser_id int ,
	parent_salesuser_name varchar(100) ,
	parent_salesuser_id_list varchar(100),
	grade int,	
    is_sales_agent int,
	call_time_long float,
	call_cus_cnt int,
	call_rec_cnt int,
	visit_cus_cnt int,
	input_cus_cnt int,
	contract_new_cnt int,
	contract_new_amount float,
	cus_contract_cnt int,
	cus_expire_cnt int,
	cus_break_cnt int,
	noincome_effect_cus_cnt int,
	lpt_income float,
	all_income float,
	add_cus_cnt int, 
	add_ejob_cnt int,
	service_cus_cnt int,
	service_ejob_cnt  int,
	creation_timestamp  timestamp default CURRENT_TIMESTAMP,
	primary key (d_date, sales_id)
);

create table dw_erp_d_contract_act
( 
d_date int,
contract_id int,
contract_no varchar(100),
contract_type varchar(50),
service_effect_date varchar(50),
service_expired_date varchar(50),
sales_id int,
sales_name varchar(100),
sales_group_id int,
sales_group_name varchar(100),
position_level varchar(20),
position_level_name varchar(50),
customer_id int,
customer_name varchar(300),
comp_industry_code varchar(20),
comp_industry_name varchar(100),
is_contract_new int,
contract_new_amount float,
is_lpt_in_service int,
is_lpt_expire int,
is_lpt_break int,
is_noincome_effect int,
lpt_income float,
all_income float,
creation_timestamp  timestamp default CURRENT_TIMESTAMP,
primary key(d_date,contract_id)
);

create table dw_erp_d_godjob_list
(
	d_date int,
	id  int,
	ejob_id int,
	ejob_title varchar(100),
	ecomp_id int,
	ecomp_root_id int,
	ecomp_name varchar(300),
	industry varchar(20),
	industry_name varchar(100),
	create_time datetime,
	is_add int,
	sales_id int,
	sales_name varchar(100),
	position_id int,
	position_name varchar(100),
	position_level varchar(20),
	position_level_name varchar(100),
	org_id int,
	org_name varchar(300),
	sales_group_id int,
	sales_group_name  varchar(100),
	ge_status varchar(2),
	creation_timestamp timestamp default CURRENT_TIMESTAMP,
	primary key (d_date, id)
) ;

create table  dim_employee_level (    
d_date int comment ' 统计日期 ',
id int  comment ' 主键 ',
name varchar(100)   comment ' 姓名 ',
parent_id int   comment ' 上级主键 ',
parent_name varchar(100)  comment ' 上级姓名 ',
parent_id_list varchar(100)  comment ' 所有上级列表，逗号分隔 ',
grade int comment ' 层级 ',
first_level int  comment ' 第1级主键 ',
first_level_name varchar(100)  comment ' 第1级姓名 ',
second_level int comment ' 第2级主键 ',
second_level_name varchar(100)  comment ' 第2级姓名 ',
third_level int  comment ' 第3级主键 ',
third_level_name varchar(100)  comment ' 第3级姓名 ',
forth_level int comment ' 第4级主键 ',
forth_level_name varchar(100)  comment ' 第4级姓名 ',
fifth_level int comment ' 第5级主键 ',
fifth_level_name varchar(100)  comment ' 第5级姓名 ',
sixth_level int comment ' 第6级主键 ',
sixth_level_name varchar(100)  comment ' 第6级姓名 ',
seventh_level int comment ' 第7级主键 ',
seventh_level_name varchar(100)  comment ' 第7级姓名 ',
eighth_level int comment ' 第8级主键 ',
eighth_level_name varchar(100)  comment ' 第8级姓名 ',
ninth_level int comment ' 第9级主键 ',
ninth_level_name varchar(100)  comment ' 第9级姓名 ',
tenth_level int comment ' 第10级主键 ',
tenth_level_name varchar(100)  comment ' 第10级姓名 ',
eleventh_level int comment ' 第11级主键 ',
eleventh_level_name varchar(100)  comment ' 第11级姓名 ',
twelfth_level int comment ' 第12级主键 ',
twelfth_level_name varchar(100)  comment ' 第12级姓名 ',
thirteenth_level int comment ' 第13级主键 ',
thirteenth_level_name varchar(100)  comment ' 第13级姓名 ',
fourteenth_level int comment ' 第14级主键 ',
fourteenth_level_name varchar(100)  comment ' 第14级姓名 ',
fifteenth_level int comment ' 第15级主键 ',
fifteenth_level_name varchar(100)  comment ' 第15级姓名 '
) ; 