create table if not exists dw_erp_d_customer_base(
id int ,
name string ,
kind int ,
dq string ,
source int ,
customer_category int ,
comp_industry string ,
comp_scale string ,
comp_kind string ,
customer_type int ,
reg_cap string ,
reg_date string ,
fax string ,
addr string ,
zip string ,
web string ,
description string ,
release_auto_type int ,
integrity int ,
level int ,
input_id int ,
service_user_id int ,
parent_id int ,
packagecust_id int ,
root_id int ,
ecomp_id int ,
ecomp_version int ,
lp_privilege_status int ,
creator_id int ,
creator_name string ,
position_channel string ,
org_id int ,
org_name string ,
create_time timestamp , 
creation_timestamp timestamp
) partitioned by (p_date int);


insert overwrite table dw_erp_d_customer_base partition(p_date = $date$) 
select 
id,
name,
dq,
source,
sign_lpt_type,
industry,
company_scale,
company_kind,
company_certificate,
cachet_certificate,
reg_cap,
reg_date,
fax,
addr,
zip,
web,
memo,
last_lock_time,
input_id,
createtime,
modifytime,
ecomp_id,
ecomp_root_id,
parent_customer_id,
is_sub_package_customer,
ecomp_version,
sales_user_id,
sales_user_name,
sales_org_id,
sales_org_name,
sales_branch_id,
sales_branch_name,
repertory_industry,
base_type,
repertory_level,
repertory_branch_id,
is_reserved,
sales_tag_ids,
release_date,
serviceuser_id,
serviceuser_name,
service_teamorg_id,
service_teamorg_name,
service_branch_id,
service_branch_name,
rps_service_version,
rsc_allocation_type,
rsc_valid_status,
rsc_valid_reason,
delete_flag,
rsc_delete_flag,
from_unixtime(unix_timestamp())  as creation_timestamp,
top_mark,
top_mark_date,
renew_intention
from dw_erp_d_customer_base_new;


insert overwrite table dw_erp_d_customer_base partition (p_date)
select 
base.id,
base.name,
base.dq,
base.source,
base.sign_lpt_type,
base.industry,
base.company_scale,
base.company_kind,
base.company_certificate,
base.cachet_certificate,
base.reg_cap,
base.reg_date,
base.fax,
base.addr,
base.zip,
base.web,
base.memo,
base.last_lock_time,
base.input_id,
base.createtime,
base.modifytime,
base.ecomp_id,
base.ecomp_root_id,
base.parent_customer_id,
base.is_sub_package_customer,
base.ecomp_version,
base.sales_user_id,
base.sales_user_name,
base.sales_org_id,
base.sales_org_name,
base.sales_branch_id,
base.sales_branch_name,
base.repertory_industry,
base.base_type,
base.repertory_level,
base.repertory_branch_id,
base.is_reserved,
base.sales_tag_ids,
base.release_date,
base.serviceuser_id,
base.serviceuser_name,
base.service_teamorg_id,
base.service_teamorg_name,
base.service_branch_id,
base.service_branch_name,
base.rps_service_version,
base.rsc_allocation_type,
base.rsc_valid_status,
base.rsc_valid_reason,
base.delete_flag,
base.rsc_delete_flag,
base.creation_timestamp,
base.top_mark,
base.top_mark_date,
nvl(rsc.renew_intention,-1),
base.p_date
from dw_erp_d_customer_base base
left join recovery.rsc_customer_extension_history_20170101_20170107 rsc 
on base.id = rsc.customer_id 
and base.p_date = rsc.p_date
where base.p_date between 20170101 and 20170107	;

insert overwrite table dw_erp_d_customer_base partition (p_date = $date$)
select 
nvl(customer.id,-1) as id,
nvl(customer.name,'未知') as name,
nvl(customer.kind,'-1') as kind,
nvl(customer.dq,'999') as dq,
nvl(customer.source,-1) as source,
nvl(customer.customer_category,-1) as customer_category,
nvl(customer.comp_industry,'999') as comp_industry,
nvl(customer.comp_scale,'-1') as comp_scale,
nvl(customer.comp_kind,'-1') as comp_kind,
nvl(customer.customer_type,-1) as customer_type,
nvl(customer.reg_cap,'-1') as reg_cap,
nvl(customer.reg_date,'1900-01-01') as reg_date,
nvl(customer.fax,'-1') as fax,
nvl(customer.addr,'-1') as addr,
nvl(customer.zip,'-1') as zip,
nvl(customer.web,'-1') as web,
nvl(customer.description,'-1') as description,
nvl(customer.release_auto_type,'-1') as release_auto_type,
nvl(customer.integrity,'-1') as integrity,
nvl(customer.level,'-1') as level,
nvl(customer.input_id,'-1') as input_id,
nvl(customer.service_user_id,'-1') as service_user_id,
nvl(customer.parent_id,'-1') as parent_id,
nvl(customer.packagecust_id,'-1') as packagecust_id,
nvl(customer.root_id,'-1') as root_id,
nvl(customer.ecomp_id,'-1') as ecomp_id,
nvl(customer.ecomp_version,'-1') as ecomp_version,
nvl(customer.lp_privilege_status,'-1') as lp_privilege_status,
nvl(customer.creator_id,-1) as creator_id,
nvl(saleuser.name,'未知') as creator_name,
nvl(saleuser.position_channel,'-1') as position_channel,
nvl(saleuser.org_id,-1) as org_id,
nvl(saleuser.org_name,-1) as org_name,
nvl( reformat_date(customer.create_time),'1900-01-01 00:00:00') as create_time,
from_unixtime(unix_timestamp())
from biz_customer customer 
left outer join 
(select id, name,position_channel,org_id,org_name
from dw_erp_d_salesuser_base 
where p_date = '$date$' ) saleuser
on customer.creator_id = saleuser.id
where contract.delete_flag = 0
and type = 1;




create table if not exists dw_erp_d_customer_base(
id int ,
name string ,
kind int ,
dq string ,
source int ,
customer_category int ,
comp_industry string ,
comp_scale string ,
comp_kind string ,
customer_type int ,
reg_cap string ,
reg_date string ,
fax string ,
addr string ,
zip string ,
web string ,
description string ,
release_auto_type int ,
integrity int ,
level int ,
input_id int ,
service_user_id int ,
parent_id int ,
packagecust_id int ,
root_id int ,
ecomp_id int ,
ecomp_version int ,
lp_privilege_status int ,
creator_id int ,
creator_name string ,
position_channel string ,
org_id int ,
org_name string ,
create_time timestamp , 
creation_timestamp timestamp
) partitioned by (p_date int);

insert overwrite table dw_erp_d_customer_base partition (p_date = $date$)
select 
nvl(customer.id,-1) as id,
nvl(customer.name,'未知') as name,
-1 as kind,
nvl(customer.dq,'999') as dq,
nvl(customer.source,-1) as source,
nvl(customer.sign_lpt_type,-1) as customer_category,
nvl(customer.industry,'999') as comp_industry,
nvl(customer.company_scale,'-1') as comp_scale,
nvl(customer.company_kind,'-1') as comp_kind,
1  as customer_type,
nvl(customer.reg_cap,'-1') as reg_cap,
nvl(customer.reg_date,'1900-01-01') as reg_date,
nvl(customer.fax,'-1') as fax,
nvl(customer.addr,'-1') as addr,
nvl(customer.zip,'-1') as zip,
nvl(customer.web,'-1') as web,
nvl(customer.memo,'-1') as description,
-1 as release_auto_type,
-1 as integrity,
-1 as level,
nvl(customer.input_id,'-1') as input_id,
nvl(customer.serviceuser_id,'-1') as service_user_id,
nvl(customer.parent_customer_id,'-1') as parent_id,
-1 as packagecust_id,
-1 as root_id,
nvl(customer.ecomp_id,'-1') as ecomp_id,
nvl(customer.ecomp_version,'-1') as ecomp_version,
-1 as lp_privilege_status,
nvl(customer.sales_user_id,-1) as creator_id,
nvl(saleuser.name,'未知') as creator_name,
nvl(saleuser.position_channel,'-1') as position_channel,
nvl(saleuser.org_id,-1) as org_id,
nvl(saleuser.org_name,-1) as org_name,
nvl(customer.createtime,'1900-01-01 00:00:00') as create_time,
from_unixtime(unix_timestamp())
from dw_erp_d_customer_base_new customer 
left outer join 
(select id, name,position_channel,org_id,org_name
from dw_erp_d_salesuser_base 
where p_date = '$date$' ) saleuser
on customer.sales_user_id = saleuser.id;